title: <p align="center>" Utkarsha Shripanavar</p>
logo: /assets/img/Biodata photo.jpg
description: I am studying AI and ML and practicing solving real world problems to be industry ready.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
